name: readio
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.7.2
dependencies:
  flutter_tts: ^4.2.2
  bloc: ^9.0.0
  cached_network_image: ^3.4.1


  cloud_firestore: ^5.6.7
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.8.0+1
  equatable: ^2.0.7
  firebase_auth: ^5.5.2
  firebase_core: ^3.13.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_lazy_indexed_stack: ^0.0.6
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.1.0
  get_it: ^8.0.3
  go_router: ^15.1.1
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.0.7
  intl: any
  meta: ^1.16.0
  modal_progress_hud_nsn: ^0.5.1
  shared_preferences: ^2.5.3
  webview_flutter: ^4.11.0
  flutter_slidable: ^4.0.0

dev_dependencies:
  build_runner: ^2.4.15

  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg_icons/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
flutter_intl:
  enabled: true
