// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1yckXxciAN7SD5kCEpy1SGxr6_qhQhaw',
    appId: '1:640609794069:web:c35583a2483ee784e3761c',
    messagingSenderId: '640609794069',
    projectId: 'readio-app-e7d47',
    authDomain: 'readio-app-e7d47.firebaseapp.com',
    storageBucket: 'readio-app-e7d47.firebasestorage.app',
    measurementId: 'G-K4CEC5XCLV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8HBNztFhJYCqpVBoqvEZeP3Bii4wOw1c',
    appId: '1:640609794069:android:f30ff1b7afadf180e3761c',
    messagingSenderId: '640609794069',
    projectId: 'readio-app-e7d47',
    storageBucket: 'readio-app-e7d47.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEzU8aY9XoAZnDB6g-F5lBsTIkb9XI-fQ',
    appId: '1:640609794069:ios:31a969e2eeb8a590e3761c',
    messagingSenderId: '640609794069',
    projectId: 'readio-app-e7d47',
    storageBucket: 'readio-app-e7d47.firebasestorage.app',
    iosBundleId: 'com.example.readio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEzU8aY9XoAZnDB6g-F5lBsTIkb9XI-fQ',
    appId: '1:640609794069:ios:31a969e2eeb8a590e3761c',
    messagingSenderId: '640609794069',
    projectId: 'readio-app-e7d47',
    storageBucket: 'readio-app-e7d47.firebasestorage.app',
    iosBundleId: 'com.example.readio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1yckXxciAN7SD5kCEpy1SGxr6_qhQhaw',
    appId: '1:640609794069:web:60ab21f0d1bb0a59e3761c',
    messagingSenderId: '640609794069',
    projectId: 'readio-app-e7d47',
    authDomain: 'readio-app-e7d47.firebaseapp.com',
    storageBucket: 'readio-app-e7d47.firebasestorage.app',
    measurementId: 'G-3S3CQ4DC7S',
  );
}
